-- Soundtrackd v2 — all migrations, generated by npm run db:bundle. Safe to run more than once.

-- ════════ 20260903000001_v1_baseline.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Soundtrackd v2 — migration 1 of 6: the v1 baseline, reconciled.
--
-- Written to be IDEMPOTENT: on the live project (where these tables already
-- exist) it only adds what is missing; on a fresh project it creates everything.
-- Apply in the Supabase SQL editor or with `supabase db push` (see SETUP.md).
-- ═══════════════════════════════════════════════════════════════════════════


-- ─── profiles ──────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  username         text not null,
  bio              text,
  pronouns         text,
  website          text,
  avatar_url       text,
  favorite_albums  jsonb default '[]'::jsonb,
  favorite_artists jsonb default '[]'::jsonb,
  created_at       timestamptz default now()
);
alter table public.profiles add column if not exists favorite_albums  jsonb default '[]'::jsonb;
alter table public.profiles add column if not exists favorite_artists jsonb default '[]'::jsonb;
-- Usernames are unique case-insensitively (live data has mixed case, e.g. "Pickledude448").
create unique index if not exists profiles_username_lower_uniq on public.profiles (lower(username));

-- ─── ratings (albums) ──────────────────────────────────────────────────────
create table if not exists public.ratings (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  album_id    text,                                 -- legacy Deezer id; catalog_item_id (migration 3) is the real key
  rating      numeric(3,1) not null,
  review      text,
  album_title text,
  album_cover text,
  created_at  timestamptz default now(),
  unique (album_id, user_id)
);
alter table public.ratings add column if not exists updated_at timestamptz default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'ratings_rating_range') then
    -- NOT VALID: enforced for new rows, existing rows are left alone.
    alter table public.ratings add constraint ratings_rating_range
      check (rating >= 0.5 and rating <= 5 and rating * 2 = floor(rating * 2)) not valid;
  end if;
end $$;

-- ─── track_ratings (songs) ─────────────────────────────────────────────────
create table if not exists public.track_ratings (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  track_id    text,                                 -- legacy Deezer id
  album_id    text,                                 -- legacy; never populated by v1 (§11 bug #4)
  rating      numeric(3,1) not null,
  review      text,
  track_title text,
  track_cover text,
  created_at  timestamptz default now(),
  unique (track_id, user_id)
);
alter table public.track_ratings add column if not exists album_id   text;
alter table public.track_ratings add column if not exists updated_at timestamptz default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'track_ratings_rating_range') then
    alter table public.track_ratings add constraint track_ratings_rating_range
      check (rating >= 0.5 and rating <= 5 and rating * 2 = floor(rating * 2)) not valid;
  end if;
end $$;

-- ─── review_likes ──────────────────────────────────────────────────────────
create table if not exists public.review_likes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  rating_id  uuid not null references public.ratings(id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, rating_id)
);

-- ─── follows ───────────────────────────────────────────────────────────────
create table if not exists public.follows (
  id           uuid primary key default gen_random_uuid(),
  follower_id  uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at   timestamptz default now()
);
create unique index if not exists follows_pair_uniq on public.follows (follower_id, following_id);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'follows_not_self') then
    alter table public.follows add constraint follows_not_self check (follower_id <> following_id) not valid;
  end if;
end $$;

-- ─── notifications ─────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  type         text not null,
  from_user_id uuid references public.profiles(id) on delete cascade,
  read         boolean default false,
  created_at   timestamptz default now()
);
alter table public.notifications add column if not exists ref_id uuid;   -- rating / friendship / conversation id

-- ─── lists ─────────────────────────────────────────────────────────────────
create table if not exists public.lists (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  title       text not null,
  description text,
  type        text not null,
  items       jsonb default '[]'::jsonb,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'lists_type_check') then
    alter table public.lists add constraint lists_type_check check (type in ('albums','songs','mixed')) not valid;
  end if;
end $$;

-- ─── indexes v1 never had (§4) ─────────────────────────────────────────────
create index if not exists ratings_album_idx         on public.ratings (album_id);
create index if not exists ratings_user_created_idx  on public.ratings (user_id, created_at desc);
create index if not exists ratings_created_idx       on public.ratings (created_at desc);
create index if not exists track_ratings_track_idx   on public.track_ratings (track_id);
create index if not exists track_ratings_user_idx    on public.track_ratings (user_id, created_at desc);
create index if not exists follows_following_idx     on public.follows (following_id);
create index if not exists follows_follower_idx      on public.follows (follower_id);
create index if not exists notifications_user_idx    on public.notifications (user_id, read, created_at desc);
create index if not exists review_likes_rating_idx   on public.review_likes (rating_id);
create index if not exists lists_user_idx            on public.lists (user_id);
create index if not exists lists_updated_idx         on public.lists (updated_at desc);

-- ─── updated_at maintenance ────────────────────────────────────────────────
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists lists_set_updated_at on public.lists;
create trigger lists_set_updated_at before update on public.lists
  for each row execute function public.set_updated_at();
drop trigger if exists ratings_set_updated_at on public.ratings;
create trigger ratings_set_updated_at before update on public.ratings
  for each row execute function public.set_updated_at();
drop trigger if exists track_ratings_set_updated_at on public.track_ratings;
create trigger track_ratings_set_updated_at before update on public.track_ratings
  for each row execute function public.set_updated_at();

-- ─── Row Level Security ────────────────────────────────────────────────────
-- v1's policies lived only in the dashboard (§4). This replaces them with the
-- canonical set so the schema is reproducible. Policies are OR-ed, so leftover
-- permissive ones would silently widen access — hence the drop-all first.
create or replace function public._drop_policies(p_table regclass) returns void language plpgsql as $$
declare pol record;
begin
  for pol in select polname from pg_policy where polrelid = p_table loop
    execute format('drop policy if exists %I on %s', pol.polname, p_table);
  end loop;
end $$;

alter table public.profiles      enable row level security;
alter table public.ratings       enable row level security;
alter table public.track_ratings enable row level security;
alter table public.review_likes  enable row level security;
alter table public.follows       enable row level security;
alter table public.notifications enable row level security;
alter table public.lists         enable row level security;

select public._drop_policies('public.profiles');
create policy "profiles: public read"   on public.profiles for select using (true);
create policy "profiles: insert own"    on public.profiles for insert with check (id = auth.uid());
create policy "profiles: update own"    on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

select public._drop_policies('public.ratings');
create policy "ratings: public read"    on public.ratings for select using (true);
create policy "ratings: insert own"     on public.ratings for insert with check (user_id = auth.uid());
create policy "ratings: update own"     on public.ratings for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "ratings: delete own"     on public.ratings for delete using (user_id = auth.uid());

select public._drop_policies('public.track_ratings');
create policy "track_ratings: public read" on public.track_ratings for select using (true);
create policy "track_ratings: insert own"  on public.track_ratings for insert with check (user_id = auth.uid());
create policy "track_ratings: update own"  on public.track_ratings for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "track_ratings: delete own"  on public.track_ratings for delete using (user_id = auth.uid());

select public._drop_policies('public.review_likes');
create policy "review_likes: public read" on public.review_likes for select using (true);
create policy "review_likes: insert own"  on public.review_likes for insert with check (user_id = auth.uid());
create policy "review_likes: delete own"  on public.review_likes for delete using (user_id = auth.uid());

select public._drop_policies('public.follows');
create policy "follows: public read"    on public.follows for select using (true);
create policy "follows: insert own"     on public.follows for insert with check (follower_id = auth.uid());
create policy "follows: delete own"     on public.follows for delete using (follower_id = auth.uid());

-- Notifications: you read and update only your own. There is deliberately NO
-- insert policy — rows are written by triggers (migration 4), so user A can
-- never forge a notification addressed to user B. This closes the "tricky one" in §4.
select public._drop_policies('public.notifications');
create policy "notifications: read own"   on public.notifications for select using (user_id = auth.uid());
create policy "notifications: update own" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "notifications: delete own" on public.notifications for delete using (user_id = auth.uid());

select public._drop_policies('public.lists');
create policy "lists: public read"      on public.lists for select using (true);
create policy "lists: insert own"       on public.lists for insert with check (user_id = auth.uid());
create policy "lists: update own"       on public.lists for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "lists: delete own"       on public.lists for delete using (user_id = auth.uid());


-- ════════ 20260903000002_auth.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 2 of 6: auth — profile creation trigger, username rules (§5).
-- Replaces v1's localStorage "pendingUsername" dance entirely.
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.profiles add column if not exists username_set boolean not null default true;

-- Username format for NEW rows (existing rows are not validated).
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_username_format') then
    alter table public.profiles add constraint profiles_username_format
      check (username ~ '^[A-Za-z0-9_]{3,20}$') not valid;
  end if;
end $$;

-- Same rules as src/lib/config.ts → keep the two lists in sync.
create or replace function public.username_available(p_username text) returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(p_username, '') ~ '^[A-Za-z0-9_]{3,20}$'
     and lower(p_username) <> all (array[
       'admin','administrator','soundtrackd','support','supporters','api','auth','login','logout',
       'signup','welcome','dash','profile','album','artist','song','search','charts','lists','list',
       'members','friends','messages','queue','settings','notifications','me'])
     and not exists (select 1 from public.profiles where lower(username) = lower(p_username));
$$;

-- Creates the profile row the moment auth.users gets a row.
--  • Password signup passes the username as auth metadata (options.data.username).
--  • Google/OAuth signups have no username: they get a placeholder and username_set = false,
--    and the app forces the choose-your-username step before anything else (§5).
--  • A username that was valid at form time but got taken in the meantime falls back to
--    the placeholder path instead of failing the whole signup.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  requested  text := trim(new.raw_user_meta_data->>'username');
  final_name text;
  is_set     boolean := false;
  avatar     text := coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture');
begin
  if requested is not null and public.username_available(requested) then
    final_name := requested;
    is_set := true;
  else
    loop
      final_name := 'listener_' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8);
      exit when not exists (select 1 from public.profiles where lower(username) = lower(final_name));
    end loop;
  end if;

  insert into public.profiles (id, username, username_set, avatar_url)
  values (new.id, final_name, is_set, avatar)
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- One-time username choice for OAuth signups (the /welcome step).
create or replace function public.set_username(p_username text) returns public.profiles
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  rec public.profiles;
begin
  if uid is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  select * into rec from public.profiles where id = uid;
  if rec.id is null then
    raise exception 'profile missing' using errcode = 'P0002';
  end if;
  if rec.username_set then
    raise exception 'username already set' using errcode = '23505';
  end if;
  if not public.username_available(p_username) then
    raise exception 'username unavailable' using errcode = '23505';
  end if;
  update public.profiles set username = p_username, username_set = true
  where id = uid returning * into rec;
  return rec;
end $$;

-- Presence: called (throttled) by the app on page loads.
alter table public.profiles add column if not exists last_seen_at timestamptz;
create or replace function public.touch_last_seen() returns void
language sql security definer set search_path = public as $$
  update public.profiles set last_seen_at = now() where id = auth.uid();
$$;


-- ════════ 20260903000003_catalog.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 3 of 6: the local canonical catalogue (§4, §6.1).
-- MBIDs are identity. Provider ids (Deezer today) are cached mappings.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.catalog_items (
  id           uuid primary key default gen_random_uuid(),
  mbid         uuid unique,                          -- MusicBrainz id. NULL only until matched.
  kind         text not null check (kind in ('album','artist','track')),
  title        text not null,
  artist_name  text,
  artist_id    uuid references public.catalog_items(id),  -- album/track → artist
  parent_id    uuid references public.catalog_items(id),  -- track → album
  release_date date,
  release_year int generated always as (extract(year from release_date)::int) stored,
  genres       text[] not null default '{}',
  cover_url    text,
  provider_ids jsonb not null default '{}'::jsonb,   -- {"deezer":"12345"} — read ONLY by the catalogue module
  record_type  text,                                 -- album | ep | single | compilation
  duration_ms  int,
  position     int,                                  -- track number within the album
  label        text,
  track_count  int,
  fetched_at   timestamptz default now(),
  created_at   timestamptz default now(),
  mbid_checked_at timestamptz                        -- last MusicBrainz lookup attempt (backfill job)
);
alter table public.catalog_items add column if not exists mbid_checked_at timestamptz;
alter table public.catalog_items add column if not exists discography_at timestamptz; -- artists: last full discography fetch

create index if not exists catalog_items_provider_ids_idx on public.catalog_items using gin (provider_ids jsonb_path_ops);
create index if not exists catalog_items_genres_idx       on public.catalog_items using gin (genres);
create index if not exists catalog_items_kind_year_idx    on public.catalog_items (kind, release_year desc);
create index if not exists catalog_items_artist_idx       on public.catalog_items (artist_id);
create index if not exists catalog_items_parent_idx       on public.catalog_items (parent_id, position);
create index if not exists catalog_items_unmatched_idx    on public.catalog_items (kind, mbid_checked_at nulls first, created_at) where mbid is null;
-- One row per (provider id, kind). Deezer album/track/artist ids are separate namespaces.
create unique index if not exists catalog_items_deezer_uniq
  on public.catalog_items (kind, (provider_ids->>'deezer')) where provider_ids ? 'deezer';

alter table public.catalog_items enable row level security;
select public._drop_policies('public.catalog_items');
create policy "catalog: public read" on public.catalog_items for select using (true);
-- No write policies on purpose: only the service role (the server-side catalogue module) writes.

-- ─── Link ratings to the catalogue ─────────────────────────────────────────
alter table public.ratings       add column if not exists catalog_item_id uuid references public.catalog_items(id);
alter table public.track_ratings add column if not exists catalog_item_id uuid references public.catalog_items(id);
alter table public.track_ratings add column if not exists album_item_id   uuid references public.catalog_items(id); -- parent album (fixes §11 #4)
alter table public.ratings       alter column album_id drop not null;
alter table public.track_ratings alter column track_id drop not null;

create unique index if not exists ratings_user_item_uniq       on public.ratings (user_id, catalog_item_id) where catalog_item_id is not null;
create unique index if not exists track_ratings_user_item_uniq on public.track_ratings (user_id, catalog_item_id) where catalog_item_id is not null;
create index if not exists ratings_item_idx        on public.ratings (catalog_item_id);
create index if not exists track_ratings_item_idx  on public.track_ratings (catalog_item_id);
create index if not exists track_ratings_album_idx on public.track_ratings (album_item_id);

-- ─── Service-role batch upsert ─────────────────────────────────────────────
-- Input: jsonb array of {kind, title, artist_name, artist_id, parent_id, release_date, genres,
-- cover_url, provider_ids, record_type, duration_ms, position, label, track_count, mbid}.
-- Matches on mbid first, then on (kind, deezer id). Returns the resulting rows in input order.
create or replace function public.catalog_upsert_items(p_items jsonb) returns setof public.catalog_items
language plpgsql security definer set search_path = public as $$
declare
  it       jsonb;
  existing public.catalog_items;
  out_row  public.catalog_items;
  v_mbid   uuid;
  v_deezer text;
  same_provider boolean;
begin
  for it in select * from jsonb_array_elements(p_items) loop
    v_mbid   := nullif(it->>'mbid', '')::uuid;
    v_deezer := it->'provider_ids'->>'deezer';

    select * into existing from public.catalog_items c
    where (v_mbid is not null and c.mbid = v_mbid)
       or (v_deezer is not null and c.kind = it->>'kind' and c.provider_ids->>'deezer' = v_deezer)
    order by (c.mbid = v_mbid) desc nulls last
    limit 1;

    if existing.id is not null then
      -- A refresh from the SAME provider is authoritative for display fields; a match across
      -- providers (by MBID) only fills blanks and merges provider ids, so a Discogs or
      -- MusicBrainz variant never renames the record everyone already rated.
      same_provider := v_deezer is not null and existing.provider_ids->>'deezer' = v_deezer;
      update public.catalog_items c set
        mbid         = coalesce(c.mbid, v_mbid),
        title        = case when same_provider then coalesce(nullif(it->>'title', ''), c.title) else c.title end,
        artist_name  = case when same_provider then coalesce(nullif(it->>'artist_name', ''), c.artist_name) else coalesce(c.artist_name, nullif(it->>'artist_name', '')) end,
        artist_id    = coalesce(c.artist_id, nullif(it->>'artist_id', '')::uuid),
        parent_id    = coalesce(c.parent_id, nullif(it->>'parent_id', '')::uuid),
        release_date = case when same_provider then coalesce(nullif(it->>'release_date', '')::date, c.release_date) else coalesce(c.release_date, nullif(it->>'release_date', '')::date) end,
        genres       = case when jsonb_typeof(it->'genres') = 'array' and jsonb_array_length(it->'genres') > 0 and (same_provider or cardinality(c.genres) = 0)
                            then array(select jsonb_array_elements_text(it->'genres')) else c.genres end,
        cover_url    = case when same_provider then coalesce(nullif(it->>'cover_url', ''), c.cover_url) else coalesce(c.cover_url, nullif(it->>'cover_url', '')) end,
        provider_ids = c.provider_ids || coalesce(it->'provider_ids', '{}'::jsonb),
        record_type  = coalesce(nullif(it->>'record_type', ''), c.record_type),
        duration_ms  = coalesce((it->>'duration_ms')::int, c.duration_ms),
        position     = coalesce((it->>'position')::int, c.position),
        label        = coalesce(nullif(it->>'label', ''), c.label),
        track_count  = coalesce((it->>'track_count')::int, c.track_count),
        fetched_at   = now()
      where c.id = existing.id
      returning * into out_row;
    else
      insert into public.catalog_items
        (mbid, kind, title, artist_name, artist_id, parent_id, release_date, genres, cover_url,
         provider_ids, record_type, duration_ms, position, label, track_count)
      values (
        v_mbid, it->>'kind', coalesce(nullif(it->>'title',''), 'Untitled'), nullif(it->>'artist_name',''),
        nullif(it->>'artist_id','')::uuid, nullif(it->>'parent_id','')::uuid,
        nullif(it->>'release_date','')::date,
        case when jsonb_typeof(it->'genres') = 'array' then array(select jsonb_array_elements_text(it->'genres')) else '{}' end,
        nullif(it->>'cover_url',''), coalesce(it->'provider_ids', '{}'::jsonb), nullif(it->>'record_type',''),
        (it->>'duration_ms')::int, (it->>'position')::int, nullif(it->>'label',''), (it->>'track_count')::int)
      returning * into out_row;
    end if;
    return next out_row;
  end loop;
end $$;
revoke execute on function public.catalog_upsert_items(jsonb) from public, anon, authenticated;

-- Records a MusicBrainz lookup (the backfill job, §7). p_mbid null = "looked, no confident match",
-- which stamps mbid_checked_at so the row is not retried every run. Service role only.
create or replace function public.catalog_set_mbid(p_id uuid, p_mbid uuid, p_cover text default null) returns void
language sql security definer set search_path = public as $$
  update public.catalog_items
  set mbid = coalesce(mbid, p_mbid), cover_url = coalesce(p_cover, cover_url), mbid_checked_at = now()
  where id = p_id;
$$;
revoke execute on function public.catalog_set_mbid(uuid, uuid, text) from public, anon, authenticated;

-- Stamps an artist row after its full discography has been fetched. Service role only.
create or replace function public.catalog_touch_discography(p_id uuid) returns void
language sql security definer set search_path = public as $$
  update public.catalog_items set discography_at = now() where id = p_id and kind = 'artist';
$$;
revoke execute on function public.catalog_touch_discography(uuid) from public, anon, authenticated;

-- ─── Rating writes: one function, both kinds (§9) ──────────────────────────
-- Upsert keyed on (user, catalog item). Also fills the legacy Deezer id columns so a row
-- rated in v1 and re-rated in v2 stays ONE row, and stamps album_item_id on track ratings.
create or replace function public.rate_item(p_kind text, p_item uuid, p_rating numeric, p_review text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid     uuid := auth.uid();
  item    public.catalog_items;
  legacy  text;
  rid     uuid;
  body    text := nullif(trim(coalesce(p_review, '')), '');
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  if p_rating is null or p_rating < 0.5 or p_rating > 5 or p_rating * 2 <> floor(p_rating * 2) then
    raise exception 'rating must be a half-step between 0.5 and 5' using errcode = '22023';
  end if;
  select * into item from public.catalog_items where id = p_item;
  if item.id is null then raise exception 'unknown catalogue item' using errcode = 'P0002'; end if;
  legacy := item.provider_ids->>'deezer';

  if p_kind = 'album' and item.kind = 'album' then
    select id into rid from public.ratings
    where user_id = uid and (catalog_item_id = p_item or (legacy is not null and album_id = legacy))
    limit 1;
    if rid is null then
      insert into public.ratings (user_id, album_id, catalog_item_id, rating, review, album_title, album_cover)
      values (uid, legacy, p_item, p_rating, body, item.title, item.cover_url)
      returning id into rid;
    else
      update public.ratings set rating = p_rating, review = body, catalog_item_id = p_item,
        album_id = coalesce(album_id, legacy), album_title = coalesce(album_title, item.title),
        album_cover = coalesce(album_cover, item.cover_url)
      where id = rid;
    end if;
  elsif p_kind = 'track' and item.kind = 'track' then
    select id into rid from public.track_ratings
    where user_id = uid and (catalog_item_id = p_item or (legacy is not null and track_id = legacy))
    limit 1;
    if rid is null then
      insert into public.track_ratings (user_id, track_id, catalog_item_id, album_item_id, rating, review, track_title, track_cover)
      values (uid, legacy, p_item, item.parent_id, p_rating, body, item.title, item.cover_url)
      returning id into rid;
    else
      update public.track_ratings set rating = p_rating, review = body, catalog_item_id = p_item,
        album_item_id = coalesce(album_item_id, item.parent_id), track_id = coalesce(track_id, legacy),
        track_title = coalesce(track_title, item.title), track_cover = coalesce(track_cover, item.cover_url)
      where id = rid;
    end if;
  else
    raise exception 'kind mismatch' using errcode = '22023';
  end if;

  return jsonb_build_object('id', rid, 'rating', p_rating, 'review', body);
end $$;

create or replace function public.unrate_item(p_kind text, p_item uuid) returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); legacy text;
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  select provider_ids->>'deezer' into legacy from public.catalog_items where id = p_item;
  if p_kind = 'album' then
    delete from public.ratings where user_id = uid and (catalog_item_id = p_item or (legacy is not null and album_id = legacy));
  else
    delete from public.track_ratings where user_id = uid and (catalog_item_id = p_item or (legacy is not null and track_id = legacy));
  end if;
end $$;


-- ════════ 20260903000004_social.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 4 of 6: friends, direct messages, presence, statuses, the listen
-- queue, list likes, message reports, and notification triggers (§4, §8.1).
--
-- Design note: friendship writes go through SECURITY DEFINER functions instead
-- of insert/update policies. The spec's policy algebra ("addressee may accept,
-- either party may block") is easy to get subtly wrong; a function with explicit
-- checks is easy to read and to test (supabase/test/run.mjs does).
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── profiles: status, presence, OAuth, supporter, queue visibility ─────────
alter table public.profiles
  add column if not exists status_text        text,
  add column if not exists status_emoji       text,
  add column if not exists status_updated_at  timestamptz,
  add column if not exists status_expires_at  timestamptz,      -- null = until manually cleared
  add column if not exists now_playing_id     uuid references public.catalog_items(id) on delete set null,
  add column if not exists now_playing_source text,
  add column if not exists now_playing_at     timestamptz,
  add column if not exists listenbrainz_user  text,
  add column if not exists accent_color       text,
  add column if not exists supporter_since    timestamptz,
  add column if not exists supporter_until    timestamptz,
  add column if not exists queue_public       boolean not null default false;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_status_len') then
    alter table public.profiles add constraint profiles_status_len check (char_length(status_text) <= 140) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_now_playing_source') then
    alter table public.profiles add constraint profiles_now_playing_source
      check (now_playing_source is null or now_playing_source in ('manual','listenbrainz','lastfm')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_accent_color_hex') then
    alter table public.profiles add constraint profiles_accent_color_hex
      check (accent_color is null or accent_color ~ '^#[0-9a-fA-F]{6}$') not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_bio_len') then
    alter table public.profiles add constraint profiles_bio_len check (char_length(bio) <= 1000) not valid;
  end if;
end $$;
create index if not exists profiles_supporter_until_idx on public.profiles (supporter_until);
create index if not exists profiles_last_seen_idx on public.profiles (last_seen_at desc);

-- ─── friendships — mutual, explicit, and the gate on DMs ───────────────────
create table if not exists public.friendships (
  id           uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status       text not null default 'pending' check (status in ('pending','accepted','blocked')),
  blocked_by   uuid references public.profiles(id) on delete cascade,
  created_at   timestamptz default now(),
  responded_at timestamptz,
  check (requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_uniq on public.friendships
  (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friendships_addressee_idx on public.friendships (addressee_id, status);
create index if not exists friendships_requester_idx on public.friendships (requester_id, status);

create or replace function public.are_friends(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and least(f.requester_id, f.addressee_id) = least(a, b)
      and greatest(f.requester_id, f.addressee_id) = greatest(a, b));
$$;

create or replace function public.is_blocked_between(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.friendships f
    where f.status = 'blocked'
      and least(f.requester_id, f.addressee_id) = least(a, b)
      and greatest(f.requester_id, f.addressee_id) = greatest(a, b));
$$;

-- Send (or, if the other person already asked you, accept) a friend request.
create or replace function public.friend_request(p_user uuid) returns public.friendships
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); f public.friendships;
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  if uid = p_user then raise exception 'you cannot friend yourself' using errcode = '22023'; end if;
  if not exists (select 1 from public.profiles where id = p_user) then
    raise exception 'no such user' using errcode = 'P0002';
  end if;

  select * into f from public.friendships
  where least(requester_id, addressee_id) = least(uid, p_user)
    and greatest(requester_id, addressee_id) = greatest(uid, p_user);

  if f.id is null then
    insert into public.friendships (requester_id, addressee_id) values (uid, p_user) returning * into f;
  elsif f.status = 'blocked' then
    raise exception 'request not possible' using errcode = '42501';
  elsif f.status = 'pending' and f.addressee_id = uid then
    update public.friendships set status = 'accepted', responded_at = now() where id = f.id returning * into f;
  end if;
  return f;
end $$;

create or replace function public.friend_respond(p_id uuid, p_accept boolean) returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  if p_accept then
    update public.friendships set status = 'accepted', responded_at = now()
    where id = p_id and addressee_id = uid and status = 'pending';
  else
    delete from public.friendships where id = p_id and addressee_id = uid and status = 'pending';
  end if;
end $$;

-- Cancel an outgoing request or unfriend. Blocks are untouched here.
create or replace function public.friend_remove(p_user uuid) returns void
language sql security definer set search_path = public as $$
  delete from public.friendships
  where status <> 'blocked'
    and least(requester_id, addressee_id) = least(auth.uid(), p_user)
    and greatest(requester_id, addressee_id) = greatest(auth.uid(), p_user);
$$;

create or replace function public.user_block(p_user uuid) returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  if uid = p_user then raise exception 'cannot block yourself' using errcode = '22023'; end if;
  delete from public.friendships
  where least(requester_id, addressee_id) = least(uid, p_user)
    and greatest(requester_id, addressee_id) = greatest(uid, p_user);
  insert into public.friendships (requester_id, addressee_id, status, blocked_by, responded_at)
  values (uid, p_user, 'blocked', uid, now());
  -- blocking also removes the follow edges in both directions
  delete from public.follows where (follower_id = uid and following_id = p_user) or (follower_id = p_user and following_id = uid);
end $$;

create or replace function public.user_unblock(p_user uuid) returns void
language sql security definer set search_path = public as $$
  delete from public.friendships
  where status = 'blocked' and blocked_by = auth.uid()
    and least(requester_id, addressee_id) = least(auth.uid(), p_user)
    and greatest(requester_id, addressee_id) = greatest(auth.uid(), p_user);
$$;

alter table public.friendships enable row level security;
select public._drop_policies('public.friendships');
create policy "friendships: parties read" on public.friendships for select
  using (auth.uid() in (requester_id, addressee_id));
-- No insert/update/delete policies: the functions above are the only writers.

-- ─── direct messages ───────────────────────────────────────────────────────
create table if not exists public.conversations (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz default now(),
  last_message_at timestamptz default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  joined_at       timestamptz default now(),
  last_read_at    timestamptz default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id       uuid not null references public.profiles(id) on delete cascade,
  body            text not null check (char_length(body) between 1 and 4000),
  shared_item_id  uuid references public.catalog_items(id) on delete set null,  -- "sending someone a record"
  created_at      timestamptz default now(),
  edited_at       timestamptz,
  deleted_at      timestamptz
);

create index if not exists messages_conversation_idx   on public.messages (conversation_id, created_at desc);
create index if not exists conversation_members_user_idx on public.conversation_members (user_id);
create index if not exists conversations_last_idx      on public.conversations (last_message_at desc);

-- SECURITY DEFINER keeps the policies readable and the recursion out (§4).
create or replace function public.is_conversation_member(p_conv uuid, p_user uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.conversation_members m where m.conversation_id = p_conv and m.user_id = p_user);
$$;

-- Member AND not blocked by / blocking any other member.
create or replace function public.can_message(p_conv uuid, p_user uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select public.is_conversation_member(p_conv, p_user)
     and not exists (
       select 1 from public.conversation_members m
       where m.conversation_id = p_conv and m.user_id <> p_user
         and public.is_blocked_between(m.user_id, p_user));
$$;

alter table public.conversations        enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages             enable row level security;

select public._drop_policies('public.conversations');
create policy "conversations: members read" on public.conversations for select
  using (public.is_conversation_member(id, auth.uid()));

select public._drop_policies('public.conversation_members');
create policy "conversation_members: members read" on public.conversation_members for select
  using (public.is_conversation_member(conversation_id, auth.uid()));

select public._drop_policies('public.messages');
create policy "messages: members read" on public.messages for select
  using (public.is_conversation_member(conversation_id, auth.uid()));
create policy "messages: members write" on public.messages for insert
  with check (sender_id = auth.uid() and deleted_at is null and public.can_message(conversation_id, auth.uid()));
create policy "messages: sender edits" on public.messages for update
  using (sender_id = auth.uid())
  with check (sender_id = auth.uid() and public.is_conversation_member(conversation_id, auth.uid()));

-- Only friends may open a conversation — enforced here, not in the UI (§8.1).
create or replace function public.get_or_create_conversation(p_user uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); conv uuid;
begin
  if uid is null then raise exception 'not signed in' using errcode = '42501'; end if;
  if uid = p_user then raise exception 'you cannot message yourself' using errcode = '22023'; end if;
  if not public.are_friends(uid, p_user) then
    raise exception 'only friends can message each other' using errcode = '42501';
  end if;

  select m1.conversation_id into conv
  from public.conversation_members m1
  join public.conversation_members m2
    on m2.conversation_id = m1.conversation_id and m2.user_id = p_user
  where m1.user_id = uid
    and (select count(*) from public.conversation_members m3 where m3.conversation_id = m1.conversation_id) = 2
  limit 1;

  if conv is null then
    insert into public.conversations default values returning id into conv;
    insert into public.conversation_members (conversation_id, user_id) values (conv, uid), (conv, p_user);
  end if;
  return conv;
end $$;

create or replace function public.mark_conversation_read(p_conv uuid) returns void
language sql security definer set search_path = public as $$
  update public.conversation_members set last_read_at = now()
  where conversation_id = p_conv and user_id = auth.uid();
  update public.notifications set read = true
  where user_id = auth.uid() and type = 'message' and ref_id = p_conv and read = false;
$$;

-- Inbox: one row per conversation for the signed-in user.
create or replace function public.conversations_overview()
returns table (
  conversation_id uuid, other_id uuid, other_username text, other_avatar text, other_accent text,
  other_supporter_until timestamptz, other_status_text text, other_status_emoji text,
  last_body text, last_at timestamptz, last_sender_id uuid, last_shared_item_id uuid, unread int
) language sql stable security definer set search_path = public as $$
  select c.id, o.id, o.username, o.avatar_url, o.accent_color, o.supporter_until, o.status_text, o.status_emoji,
         lm.body, lm.created_at, lm.sender_id, lm.shared_item_id,
         (select count(*)::int from public.messages x
           where x.conversation_id = c.id and x.sender_id <> me.user_id
             and x.created_at > me.last_read_at and x.deleted_at is null)
  from public.conversation_members me
  join public.conversations c on c.id = me.conversation_id
  join public.conversation_members om on om.conversation_id = c.id and om.user_id <> me.user_id
  join public.profiles o on o.id = om.user_id
  left join lateral (
    select body, created_at, sender_id, shared_item_id from public.messages m
    where m.conversation_id = c.id and m.deleted_at is null
    order by created_at desc limit 1) lm on true
  where me.user_id = auth.uid()
  order by c.last_message_at desc;
$$;

-- ─── message reports (the report/block path ships with messaging, §8.1) ────
create table if not exists public.message_reports (
  id          uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  message_id  uuid not null references public.messages(id) on delete cascade,
  reason      text check (char_length(reason) <= 500),
  created_at  timestamptz default now(),
  unique (reporter_id, message_id)
);
alter table public.message_reports enable row level security;
select public._drop_policies('public.message_reports');
create policy "message_reports: insert own" on public.message_reports for insert
  with check (reporter_id = auth.uid()
    and exists (select 1 from public.messages m where m.id = message_id and public.is_conversation_member(m.conversation_id, auth.uid())));
-- No select policy for users: reports are read by the owner in the dashboard.

-- ─── listen queue — "to be listened to" (§8.1) ─────────────────────────────
create table if not exists public.listen_queue (
  user_id         uuid not null references public.profiles(id) on delete cascade,
  catalog_item_id uuid not null references public.catalog_items(id) on delete cascade,
  note            text check (char_length(note) <= 280),
  added_at        timestamptz default now(),
  primary key (user_id, catalog_item_id)
);
create index if not exists listen_queue_user_idx on public.listen_queue (user_id, added_at desc);

alter table public.listen_queue enable row level security;
select public._drop_policies('public.listen_queue');
-- Private by default; visible to others only if the owner flipped profiles.queue_public.
create policy "listen_queue: owner or public" on public.listen_queue for select
  using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = user_id and p.queue_public));
create policy "listen_queue: insert own" on public.listen_queue for insert with check (user_id = auth.uid());
create policy "listen_queue: update own" on public.listen_queue for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "listen_queue: delete own" on public.listen_queue for delete using (user_id = auth.uid());

-- ─── list likes (powers the "likes" sort in §8.3) ──────────────────────────
create table if not exists public.list_likes (
  user_id    uuid not null references public.profiles(id) on delete cascade,
  list_id    uuid not null references public.lists(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, list_id)
);
create index if not exists list_likes_list_idx on public.list_likes (list_id);
alter table public.list_likes enable row level security;
select public._drop_policies('public.list_likes');
create policy "list_likes: public read" on public.list_likes for select using (true);
create policy "list_likes: insert own"  on public.list_likes for insert with check (user_id = auth.uid());
create policy "list_likes: delete own"  on public.list_likes for delete using (user_id = auth.uid());

-- ─── notifications: types + triggers ───────────────────────────────────────
-- Replace, don't skip: v1 may already have a same-named check that only allows the two old types.
alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications add constraint notifications_type_check
  check (type in ('follow','review_like','friend_request','friend_accepted','message')) not valid;

create or replace function public.notify_on_follow() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications (user_id, type, from_user_id) values (new.following_id, 'follow', new.follower_id);
  return new;
end $$;
drop trigger if exists follows_notify on public.follows;
create trigger follows_notify after insert on public.follows for each row execute function public.notify_on_follow();

create or replace function public.notify_on_review_like() returns trigger
language plpgsql security definer set search_path = public as $$
declare owner uuid;
begin
  select user_id into owner from public.ratings where id = new.rating_id;
  if owner is not null and owner <> new.user_id then   -- skipped when you like your own review (§9)
    insert into public.notifications (user_id, type, from_user_id, ref_id) values (owner, 'review_like', new.user_id, new.rating_id);
  end if;
  return new;
end $$;
drop trigger if exists review_likes_notify on public.review_likes;
create trigger review_likes_notify after insert on public.review_likes for each row execute function public.notify_on_review_like();

create or replace function public.notify_on_friendship() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    insert into public.notifications (user_id, type, from_user_id, ref_id) values (new.addressee_id, 'friend_request', new.requester_id, new.id);
  elsif tg_op = 'UPDATE' and old.status = 'pending' and new.status = 'accepted' then
    insert into public.notifications (user_id, type, from_user_id, ref_id) values (new.requester_id, 'friend_accepted', new.addressee_id, new.id);
    update public.notifications set read = true where type = 'friend_request' and ref_id = new.id;
  end if;
  return new;
end $$;
drop trigger if exists friendships_notify on public.friendships;
create trigger friendships_notify after insert or update on public.friendships for each row execute function public.notify_on_friendship();

create or replace function public.on_message_insert() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update public.conversations set last_message_at = new.created_at where id = new.conversation_id;
  -- one unread "message" notification per conversation, not one per message
  insert into public.notifications (user_id, type, from_user_id, ref_id)
  select m.user_id, 'message', new.sender_id, new.conversation_id
  from public.conversation_members m
  where m.conversation_id = new.conversation_id and m.user_id <> new.sender_id
    and not exists (select 1 from public.notifications n
                    where n.user_id = m.user_id and n.type = 'message' and n.ref_id = new.conversation_id and n.read = false);
  return new;
end $$;
drop trigger if exists messages_after_insert on public.messages;
create trigger messages_after_insert after insert on public.messages for each row execute function public.on_message_insert();

-- Unread badges for the nav.
create or replace function public.unread_counts() returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'notifications', (select count(*) from public.notifications where user_id = auth.uid() and read = false),
    'messages', (select count(*) from public.conversation_members cm
                  where cm.user_id = auth.uid()
                    and exists (select 1 from public.messages m
                                where m.conversation_id = cm.conversation_id and m.sender_id <> cm.user_id
                                  and m.created_at > cm.last_read_at and m.deleted_at is null)));
$$;

-- ─── Realtime: chat subscribes to messages (RLS still applies) ─────────────
do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
      alter publication supabase_realtime add table public.messages;
    end if;
  end if;
end $$;


-- ════════ 20260903000005_aggregates.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 5 of 6: aggregates in Postgres (§11 bug #3) and the parameterised
-- sort/filter functions behind §8.3. Nothing in the browser reduces rows.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── stats views ───────────────────────────────────────────────────────────
create or replace view public.album_stats with (security_invoker = true) as
  select catalog_item_id,
         count(*)::int                                            as rating_count,
         round(avg(rating)::numeric, 2)::float                     as avg_rating,
         count(*) filter (where nullif(review, '') is not null)::int as review_count
  from public.ratings
  where catalog_item_id is not null
  group by catalog_item_id;

create or replace view public.track_stats with (security_invoker = true) as
  select catalog_item_id,
         count(*)::int                                            as rating_count,
         round(avg(rating)::numeric, 2)::float                     as avg_rating,
         count(*) filter (where nullif(review, '') is not null)::int as review_count
  from public.track_ratings
  where catalog_item_id is not null
  group by catalog_item_id;

-- Ten half-star buckets, zero-filled, for the distribution bar chart.
create or replace function public.rating_distribution(p_kind text, p_item uuid)
returns table (bucket numeric, n int) language sql stable as $$
  with buckets as (select unnest(array[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5]::numeric[]) as bucket),
  counts as (
    select rating, count(*) as n from public.ratings where p_kind = 'album' and catalog_item_id = p_item group by rating
    union all
    select rating, count(*) as n from public.track_ratings where p_kind = 'track' and catalog_item_id = p_item group by rating)
  select b.bucket, coalesce(c.n, 0)::int from buckets b left join counts c on c.rating = b.bucket order by b.bucket;
$$;

-- Site-wide score distribution (charts page stats block).
create or replace function public.community_distribution()
returns table (bucket numeric, n int) language sql stable as $$
  with buckets as (select unnest(array[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5]::numeric[]) as bucket)
  select b.bucket, coalesce((select count(*) from public.ratings r where r.rating = b.bucket), 0)::int
  from buckets b order by b.bucket;
$$;

-- ─── reviews & friends on an item ──────────────────────────────────────────
create or replace function public.reviews_for_item(p_kind text, p_item uuid, p_sort text default 'recent', p_limit int default 20, p_offset int default 0)
returns table (
  id uuid, user_id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz,
  rating numeric, review text, created_at timestamptz, like_count int, liked_by_me boolean
) language sql stable as $$
  select * from (
    select r.id, r.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
           r.rating, r.review, r.created_at,
           (select count(*)::int from public.review_likes l where l.rating_id = r.id) as like_count,
           exists (select 1 from public.review_likes l where l.rating_id = r.id and l.user_id = auth.uid()) as liked_by_me
    from public.ratings r join public.profiles p on p.id = r.user_id
    where p_kind = 'album' and r.catalog_item_id = p_item and nullif(r.review, '') is not null
    union all
    select t.id, t.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
           t.rating, t.review, t.created_at, 0, false
    from public.track_ratings t join public.profiles p on p.id = t.user_id
    where p_kind = 'track' and t.catalog_item_id = p_item and nullif(t.review, '') is not null
  ) x
  order by case when p_sort = 'top' then x.like_count end desc nulls last, x.created_at desc
  limit p_limit offset p_offset;
$$;

-- What people you follow rated this (the friends panel on album pages).
create or replace function public.followed_ratings_for_item(p_kind text, p_item uuid, p_limit int default 12)
returns table (user_id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz, rating numeric, has_review boolean, created_at timestamptz)
language sql stable as $$
  select p.id, p.username, p.avatar_url, p.accent_color, p.supporter_until, x.rating, x.has_review, x.created_at
  from (
    select user_id, rating, nullif(review,'') is not null as has_review, created_at from public.ratings where p_kind = 'album' and catalog_item_id = p_item
    union all
    select user_id, rating, nullif(review,'') is not null, created_at from public.track_ratings where p_kind = 'track' and catalog_item_id = p_item
  ) x
  join public.follows f on f.following_id = x.user_id and f.follower_id = auth.uid()
  join public.profiles p on p.id = x.user_id
  order by x.created_at desc limit p_limit;
$$;

-- ─── profile ───────────────────────────────────────────────────────────────
create or replace function public.profile_stats(p_user uuid) returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'ratings',       (select count(*) from public.ratings where user_id = p_user),
    'reviews',       (select count(*) from public.ratings where user_id = p_user and nullif(review,'') is not null),
    'track_ratings', (select count(*) from public.track_ratings where user_id = p_user),
    'lists',         (select count(*) from public.lists where user_id = p_user),
    'followers',     (select count(*) from public.follows where following_id = p_user),
    'following',     (select count(*) from public.follows where follower_id = p_user),
    'friends',       (select count(*) from public.friendships where status = 'accepted' and p_user in (requester_id, addressee_id)),
    'avg_rating',    (select round(avg(rating)::numeric, 2) from public.ratings where user_id = p_user),
    'this_month',    (select count(*) from public.ratings where user_id = p_user and created_at >= date_trunc('month', now())),
    'distribution',  (select jsonb_agg(jsonb_build_object('bucket', b.bucket, 'n', coalesce(c.n, 0)) order by b.bucket)
                      from (select unnest(array[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5]::numeric[]) as bucket) b
                      left join (select rating, count(*) as n from public.ratings where user_id = p_user group by rating) c on c.rating = b.bucket)
  );
$$;

-- Review history with §8.3 sorting/filtering, joined to the catalogue.
create or replace function public.user_ratings(
  p_user uuid, p_sort text default 'date', p_dir text default 'desc',
  p_min numeric default null, p_max numeric default null, p_year int default null,
  p_genre text default null, p_reviewed boolean default null,
  p_limit int default 40, p_offset int default 0
) returns table (
  id uuid, catalog_item_id uuid, legacy_album_id text, title text, artist_name text, artist_id uuid, cover_url text,
  release_year int, genres text[], rating numeric, review text, created_at timestamptz, like_count int
) language sql stable as $$
  select r.id, r.catalog_item_id, r.album_id,
         coalesce(ci.title, r.album_title) as title, ci.artist_name, ci.artist_id,
         coalesce(ci.cover_url, r.album_cover) as cover_url, ci.release_year, coalesce(ci.genres, '{}'),
         r.rating, r.review, r.created_at,
         (select count(*)::int from public.review_likes l where l.rating_id = r.id)
  from public.ratings r
  left join public.catalog_items ci on ci.id = r.catalog_item_id
  where r.user_id = p_user
    and (p_min is null or r.rating >= p_min)
    and (p_max is null or r.rating <= p_max)
    and (p_year is null or ci.release_year = p_year)
    and (p_genre is null or p_genre = any(ci.genres))
    and (p_reviewed is null or (nullif(r.review,'') is not null) = p_reviewed)
  order by
    case when p_dir = 'asc'  then case p_sort when 'rating' then r.rating when 'year' then ci.release_year::numeric end end asc  nulls last,
    case when p_dir = 'desc' then case p_sort when 'rating' then r.rating when 'year' then ci.release_year::numeric end end desc nulls last,
    case when p_dir = 'asc'  then case p_sort when 'artist' then lower(coalesce(ci.artist_name,'')) when 'title' then lower(coalesce(ci.title, r.album_title, '')) end end asc,
    case when p_dir = 'desc' then case p_sort when 'artist' then lower(coalesce(ci.artist_name,'')) when 'title' then lower(coalesce(ci.title, r.album_title, '')) end end desc,
    case when p_dir = 'asc' and p_sort = 'date' then r.created_at end asc,
    r.created_at desc
  limit p_limit offset p_offset;
$$;

-- ─── the feed (§8.2 module 1) ──────────────────────────────────────────────
create or replace function public.activity_feed(p_limit int default 30, p_before timestamptz default null)
returns table (kind text, id uuid, actor_id uuid, actor_username text, actor_avatar text, actor_accent text,
               actor_supporter_until timestamptz, created_at timestamptz, payload jsonb)
language sql stable as $$
  with who as (select following_id as id from public.follows where follower_id = auth.uid())
  select * from (
    select 'rating'::text, r.id, r.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, r.created_at,
           jsonb_build_object('item_id', r.catalog_item_id, 'legacy_album_id', r.album_id,
             'title', coalesce(ci.title, r.album_title), 'artist', ci.artist_name,
             'cover', coalesce(ci.cover_url, r.album_cover), 'rating', r.rating, 'review', r.review,
             'like_count', (select count(*) from public.review_likes l where l.rating_id = r.id),
             'liked_by_me', exists (select 1 from public.review_likes l where l.rating_id = r.id and l.user_id = auth.uid()))
    from public.ratings r join who on who.id = r.user_id join public.profiles p on p.id = r.user_id
    left join public.catalog_items ci on ci.id = r.catalog_item_id
    union all
    select 'track_rating', t.id, t.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, t.created_at,
           jsonb_build_object('item_id', t.catalog_item_id, 'album_item_id', t.album_item_id,
             'title', coalesce(ci.title, t.track_title), 'artist', ci.artist_name,
             'cover', coalesce(ci.cover_url, t.track_cover), 'rating', t.rating, 'review', t.review)
    from public.track_ratings t join who on who.id = t.user_id join public.profiles p on p.id = t.user_id
    left join public.catalog_items ci on ci.id = t.catalog_item_id
    union all
    select 'list', l.id, l.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, l.created_at,
           jsonb_build_object('title', l.title, 'type', l.type, 'item_count', jsonb_array_length(coalesce(l.items, '[]'::jsonb)),
             'covers', (select jsonb_agg(i->>'cover') from (select i from jsonb_array_elements(coalesce(l.items,'[]'::jsonb)) i limit 4) s))
    from public.lists l join who on who.id = l.user_id join public.profiles p on p.id = l.user_id
    union all
    select 'friendship', f.id, f.requester_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, f.responded_at,
           jsonb_build_object('other_id', o.id, 'other_username', o.username, 'other_avatar', o.avatar_url)
    from public.friendships f
    join who on who.id in (f.requester_id, f.addressee_id)
    join public.profiles p on p.id = f.requester_id
    join public.profiles o on o.id = f.addressee_id
    where f.status = 'accepted' and f.responded_at is not null
  ) x
  where p_before is null or x.created_at < p_before
  order by x.created_at desc
  limit p_limit;
$$;

-- ─── charts (§8 charts, §8.3) ──────────────────────────────────────────────
create or replace function public.charts_albums(
  p_sort text default 'rating', p_genre text default null, p_decade int default null, p_year int default null,
  p_min int default 1, p_limit int default 50, p_offset int default 0
) returns table (
  id uuid, title text, artist_name text, artist_id uuid, cover_url text, release_year int, genres text[],
  rating_count int, avg_rating float, review_count int, recent_count int
) language sql stable as $$
  select ci.id, ci.title, ci.artist_name, ci.artist_id, ci.cover_url, ci.release_year, ci.genres,
         s.rating_count, s.avg_rating, s.review_count,
         (select count(*)::int from public.ratings r where r.catalog_item_id = ci.id and r.created_at > now() - interval '7 days') as recent_count
  from public.album_stats s
  join public.catalog_items ci on ci.id = s.catalog_item_id
  where ci.kind = 'album' and s.rating_count >= p_min
    and (p_genre is null or p_genre = any(ci.genres))
    and (p_decade is null or ci.release_year between p_decade and p_decade + 9)
    and (p_year is null or ci.release_year = p_year)
  order by
    case p_sort when 'rating' then s.avg_rating end desc nulls last,
    case p_sort when 'reviews' then s.review_count end desc,
    case p_sort when 'count' then s.rating_count end desc,
    case p_sort when 'trending' then (select count(*) from public.ratings r where r.catalog_item_id = ci.id and r.created_at > now() - interval '7 days') end desc,
    s.rating_count desc, ci.title
  limit p_limit offset p_offset;
$$;

create or replace function public.charts_tracks(p_sort text default 'rating', p_min int default 1, p_limit int default 50, p_offset int default 0)
returns table (id uuid, title text, artist_name text, artist_id uuid, parent_id uuid, cover_url text, release_year int, rating_count int, avg_rating float)
language sql stable as $$
  select ci.id, ci.title, ci.artist_name, ci.artist_id, ci.parent_id, ci.cover_url, ci.release_year, s.rating_count, s.avg_rating
  from public.track_stats s join public.catalog_items ci on ci.id = s.catalog_item_id
  where ci.kind = 'track' and s.rating_count >= p_min
  order by case p_sort when 'rating' then s.avg_rating end desc nulls last,
           case p_sort when 'count' then s.rating_count end desc,
           s.rating_count desc, ci.title
  limit p_limit offset p_offset;
$$;

-- Distinct genres that actually have rated albums (filter dropdowns).
create or replace function public.rated_genres(p_limit int default 40)
returns table (genre text, n int) language sql stable as $$
  select g, count(*)::int from public.catalog_items ci, unnest(ci.genres) g
  where ci.kind = 'album' and exists (select 1 from public.ratings r where r.catalog_item_id = ci.id)
  group by g order by 2 desc, 1 limit p_limit;
$$;

-- ─── members directory ─────────────────────────────────────────────────────
create or replace function public.members_directory(p_q text default null, p_sort text default 'joined', p_limit int default 60, p_offset int default 0)
returns table (id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz, created_at timestamptz,
               review_count int, status_text text, status_emoji text, last_seen_at timestamptz)
language sql stable as $$
  select p.id, p.username, p.avatar_url, p.accent_color, p.supporter_until, p.created_at,
         (select count(*)::int from public.ratings r where r.user_id = p.id) as review_count,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_text end,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_emoji end,
         p.last_seen_at
  from public.profiles p
  where p.username_set and (p_q is null or p.username ilike '%' || p_q || '%')
  order by case p_sort when 'reviews' then (select count(*) from public.ratings r where r.user_id = p.id) end desc,
           case p_sort when 'username' then lower(p.username) end asc,
           case p_sort when 'active' then p.last_seen_at end desc nulls last,
           p.created_at desc
  limit p_limit offset p_offset;
$$;

-- ─── lists directory ───────────────────────────────────────────────────────
create or replace function public.lists_directory(p_sort text default 'updated', p_type text default null, p_user uuid default null, p_limit int default 40, p_offset int default 0)
returns table (id uuid, user_id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz,
               title text, description text, type text, items jsonb, item_count int, like_count int, liked_by_me boolean,
               created_at timestamptz, updated_at timestamptz)
language sql stable as $$
  select l.id, l.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
         l.title, l.description, l.type, coalesce(l.items, '[]'::jsonb),
         jsonb_array_length(coalesce(l.items, '[]'::jsonb)),
         (select count(*)::int from public.list_likes k where k.list_id = l.id),
         exists (select 1 from public.list_likes k where k.list_id = l.id and k.user_id = auth.uid()),
         l.created_at, l.updated_at
  from public.lists l join public.profiles p on p.id = l.user_id
  where (p_type is null or l.type = p_type) and (p_user is null or l.user_id = p_user)
  order by case p_sort when 'likes' then (select count(*) from public.list_likes k where k.list_id = l.id) end desc,
           case p_sort when 'items' then jsonb_array_length(coalesce(l.items, '[]'::jsonb)) end desc,
           case p_sort when 'created' then l.created_at end desc,
           l.updated_at desc
  limit p_limit offset p_offset;
$$;

-- ─── listen queue (§8.1, §8.3) ─────────────────────────────────────────────
create or replace function public.queue_list(p_user uuid default null, p_sort text default 'added', p_dir text default 'desc', p_genre text default null, p_decade int default null)
returns table (catalog_item_id uuid, note text, added_at timestamptz, title text, artist_name text, artist_id uuid,
               cover_url text, release_year int, genres text[], rating_count int, avg_rating float)
language sql stable as $$
  select q.catalog_item_id, q.note, q.added_at, ci.title, ci.artist_name, ci.artist_id, ci.cover_url, ci.release_year, ci.genres,
         coalesce(s.rating_count, 0), s.avg_rating
  from public.listen_queue q
  join public.catalog_items ci on ci.id = q.catalog_item_id
  left join public.album_stats s on s.catalog_item_id = ci.id
  where q.user_id = coalesce(p_user, auth.uid())
    and (p_genre is null or p_genre = any(ci.genres))
    and (p_decade is null or ci.release_year between p_decade and p_decade + 9)
  order by
    case when p_dir = 'asc'  then case p_sort when 'year' then ci.release_year::numeric when 'rating' then s.avg_rating::numeric end end asc  nulls last,
    case when p_dir = 'desc' then case p_sort when 'year' then ci.release_year::numeric when 'rating' then s.avg_rating::numeric end end desc nulls last,
    case when p_dir = 'asc'  then case p_sort when 'artist' then lower(coalesce(ci.artist_name,'')) end end asc,
    case when p_dir = 'desc' then case p_sort when 'artist' then lower(coalesce(ci.artist_name,'')) end end desc,
    case when p_dir = 'asc' and p_sort = 'added' then q.added_at end asc,
    q.added_at desc;
$$;

-- ─── artist discography with community + your rating ───────────────────────
create or replace function public.artist_discography(p_artist uuid, p_sort text default 'year', p_dir text default 'desc', p_type text default null, p_decade int default null)
returns table (id uuid, title text, cover_url text, release_year int, release_date date, record_type text, genres text[],
               rating_count int, avg_rating float, my_rating numeric)
language sql stable as $$
  select ci.id, ci.title, ci.cover_url, ci.release_year, ci.release_date, ci.record_type, ci.genres,
         coalesce(s.rating_count, 0), s.avg_rating,
         (select r.rating from public.ratings r where r.catalog_item_id = ci.id and r.user_id = auth.uid())
  from public.catalog_items ci
  left join public.album_stats s on s.catalog_item_id = ci.id
  where ci.kind = 'album' and ci.artist_id = p_artist
    and (p_type is null or ci.record_type = p_type)
    and (p_decade is null or ci.release_year between p_decade and p_decade + 9)
  order by
    case when p_dir = 'asc'  then case p_sort when 'year' then ci.release_date::text when 'rating' then s.avg_rating::text when 'mine' then (select r.rating::text from public.ratings r where r.catalog_item_id = ci.id and r.user_id = auth.uid()) when 'title' then lower(ci.title) end end asc  nulls last,
    case when p_dir = 'desc' then case p_sort when 'year' then ci.release_date::text when 'rating' then lpad(s.avg_rating::text, 5, '0') when 'mine' then (select r.rating::text from public.ratings r where r.catalog_item_id = ci.id and r.user_id = auth.uid()) when 'title' then lower(ci.title) end end desc nulls last,
    ci.release_date desc nulls last, ci.title;
$$;

-- ─── dashboard modules (§8.2) ──────────────────────────────────────────────
create or replace function public.friends_now_playing()
returns table (id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz,
               status_text text, status_emoji text, last_seen_at timestamptz,
               now_playing_id uuid, now_playing_at timestamptz, now_playing_source text,
               np_title text, np_artist text, np_cover text)
language sql stable as $$
  select p.id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_text end,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_emoji end,
         p.last_seen_at,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_id end,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_at end,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_source end,
         ci.title, ci.artist_name, ci.cover_url
  from public.friendships f
  join public.profiles p on p.id = case when f.requester_id = auth.uid() then f.addressee_id else f.requester_id end
  left join public.catalog_items ci on ci.id = p.now_playing_id and p.now_playing_at > now() - interval '30 minutes'
  where f.status = 'accepted' and auth.uid() in (f.requester_id, f.addressee_id)
  order by (p.now_playing_at > now() - interval '30 minutes') desc nulls last, p.last_seen_at desc nulls last;
$$;

-- New releases from artists you've rated 4+ (§8.2 module 5): a join, not a recommender.
create or replace function public.new_releases_for_user(p_days int default 120, p_limit int default 12)
returns table (id uuid, title text, artist_name text, artist_id uuid, cover_url text, release_date date, record_type text)
language sql stable as $$
  with liked_artists as (
    select distinct ci.artist_id from public.ratings r
    join public.catalog_items ci on ci.id = r.catalog_item_id
    where r.user_id = auth.uid() and r.rating >= 4 and ci.artist_id is not null)
  select a.id, a.title, a.artist_name, a.artist_id, a.cover_url, a.release_date, a.record_type
  from public.catalog_items a
  join liked_artists la on la.artist_id = a.artist_id
  where a.kind = 'album' and a.release_date >= current_date - p_days
    and not exists (select 1 from public.ratings r where r.catalog_item_id = a.id and r.user_id = auth.uid())
  order by a.release_date desc limit p_limit;
$$;

-- Social proof for the landing page and the dashboard community module.
create or replace function public.recent_reviews(p_limit int default 8)
returns table (id uuid, user_id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz,
               item_id uuid, legacy_album_id text, title text, artist_name text, cover_url text,
               rating numeric, review text, created_at timestamptz, like_count int)
language sql stable as $$
  select r.id, r.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
         r.catalog_item_id, r.album_id, coalesce(ci.title, r.album_title), ci.artist_name, coalesce(ci.cover_url, r.album_cover),
         r.rating, r.review, r.created_at,
         (select count(*)::int from public.review_likes l where l.rating_id = r.id)
  from public.ratings r join public.profiles p on p.id = r.user_id
  left join public.catalog_items ci on ci.id = r.catalog_item_id
  where nullif(r.review, '') is not null
  order by r.created_at desc limit p_limit;
$$;

-- Ratings on many items at once for grids (community + yours).
create or replace function public.item_stats(p_ids uuid[])
returns table (catalog_item_id uuid, rating_count int, avg_rating float, my_rating numeric)
language sql stable as $$
  select ci.id, coalesce(s.rating_count, 0), s.avg_rating,
         (select r.rating from public.ratings r where r.catalog_item_id = ci.id and r.user_id = auth.uid())
  from public.catalog_items ci
  left join public.album_stats s on s.catalog_item_id = ci.id
  where ci.id = any(p_ids);
$$;

create or replace function public.track_item_stats(p_ids uuid[])
returns table (catalog_item_id uuid, rating_count int, avg_rating float, my_rating numeric)
language sql stable as $$
  select ci.id, coalesce(s.rating_count, 0), s.avg_rating,
         (select t.rating from public.track_ratings t where t.catalog_item_id = ci.id and t.user_id = auth.uid())
  from public.catalog_items ci
  left join public.track_stats s on s.catalog_item_id = ci.id
  where ci.id = any(p_ids);
$$;


-- ════════ 20260903000006_supporter.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 6 of 6: the single supporter tier (§13.2B) — cosmetic only.
-- Only the payment webhook (service role) grants supporter status.
-- Lapsing is non-destructive: the badge stops rendering, nothing else changes.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.subscriptions (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references public.profiles(id) on delete cascade,
  provider                 text not null,
  provider_customer_id     text,
  provider_subscription_id text not null,
  status                   text not null check (status in ('active','lapsed','cancelled')),
  current_period_end       timestamptz,
  created_at               timestamptz default now(),
  updated_at               timestamptz default now(),
  unique (provider, provider_subscription_id)
);
create index if not exists subscriptions_user_idx on public.subscriptions (user_id);

alter table public.subscriptions enable row level security;
select public._drop_policies('public.subscriptions');
create policy "subscriptions: read own" on public.subscriptions for select using (user_id = auth.uid());
-- No write policies: the webhook handler uses the service role.

-- The entitlement rule, in SQL. Mirrors isSupporter() in src/lib/entitlements.ts.
-- Usable as a computed column in PostgREST: profiles?select=*,is_supporter
create or replace function public.is_supporter(p public.profiles) returns boolean
language sql stable as $$
  select p.supporter_until is not null and p.supporter_until > now();
$$;

create or replace view public.supporters_public with (security_invoker = true) as
  select id, username, avatar_url, accent_color, supporter_since
  from public.profiles
  where supporter_until is not null and supporter_until > now()
  order by supporter_since asc nulls last;

-- Applied by the webhook. Idempotent: the same event twice leaves the same state.
create or replace function public.apply_subscription_event(
  p_provider text, p_subscription_id text, p_customer_id text, p_user uuid,
  p_status text, p_period_end timestamptz
) returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.subscriptions (user_id, provider, provider_customer_id, provider_subscription_id, status, current_period_end)
  values (p_user, p_provider, p_customer_id, p_subscription_id, p_status, p_period_end)
  on conflict (provider, provider_subscription_id) do update
    set status = excluded.status,
        current_period_end = excluded.current_period_end,
        provider_customer_id = coalesce(excluded.provider_customer_id, public.subscriptions.provider_customer_id),
        updated_at = now();

  if p_status = 'active' then
    update public.profiles
    set supporter_since = coalesce(supporter_since, now()),
        supporter_until = greatest(coalesce(supporter_until, p_period_end), p_period_end)
    where id = p_user;
  else
    -- lapsed/cancelled: access runs to the end of the paid period, then stops. Nothing is deleted.
    update public.profiles set supporter_until = least(coalesce(supporter_until, p_period_end), coalesce(p_period_end, now()))
    where id = p_user;
  end if;
end $$;
revoke execute on function public.apply_subscription_event(text, text, text, uuid, text, timestamptz) from public, anon, authenticated;

-- ─── Column protection on profiles ─────────────────────────────────────────
-- "update own row" RLS would otherwise let a user write their own supporter_until, rename
-- themselves, or flip username_set and re-run the welcome step. Only the service role (the
-- webhook / jobs) and set_username() (which sets a session flag) may touch these columns.
create or replace function public.protect_profile_columns() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  is_user boolean := auth.uid() is not null;   -- a signed-in user's JWT; service role has none
  allow_username boolean := coalesce(current_setting('soundtrackd.allow_username_change', true), '') = '1';
begin
  if is_user then
    new.supporter_since := old.supporter_since;
    new.supporter_until := old.supporter_until;
    new.id := old.id;
    new.created_at := old.created_at;
    if not allow_username then
      new.username := old.username;
      new.username_set := old.username_set;
    end if;
    -- users can only ever set the manual now-playing source; pollers set the others
    if new.now_playing_source is distinct from old.now_playing_source and new.now_playing_source <> 'manual' then
      new.now_playing_source := 'manual';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists profiles_protect_columns on public.profiles;
create trigger profiles_protect_columns before update on public.profiles
  for each row execute function public.protect_profile_columns();

-- set_username() is the one sanctioned username write: it raises the flag for its own transaction.
create or replace function public.set_username(p_username text) returns public.profiles
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  rec public.profiles;
begin
  if uid is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  select * into rec from public.profiles where id = uid;
  if rec.id is null then
    raise exception 'profile missing' using errcode = 'P0002';
  end if;
  if rec.username_set then
    raise exception 'username already set' using errcode = '23505';
  end if;
  if not public.username_available(p_username) then
    raise exception 'username unavailable' using errcode = '23505';
  end if;
  perform set_config('soundtrackd.allow_username_change', '1', true);
  update public.profiles set username = p_username, username_set = true
  where id = uid returning * into rec;
  perform set_config('soundtrackd.allow_username_change', '', true);
  return rec;
end $$;


-- ════════ 20260903000007_app_cache.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 7: a small server-side cache (§9 "cache at the edge/server so the
-- benefit is shared across all users"). Holds things like the Last.fm trending
-- list so a cold serverless instance doesn't recompute them. Service role only.
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.app_cache (
  key        text primary key,
  value      jsonb not null,
  expires_at timestamptz not null,
  updated_at timestamptz default now()
);
alter table public.app_cache enable row level security;
select public._drop_policies('public.app_cache');
-- no policies: only the service role reads or writes this table


-- ════════ 20260903000008_mutual_follows.sql ════════

-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 8: friends are mutual follows (the Letterboxd model).
-- A one-way follow puts someone's activity in your feed. When both follow each
-- other they are friends, which is what unlocks messaging. The request/accept
-- flow from migration 4 is removed; blocks stay explicit in `friendships`.
-- ═══════════════════════════════════════════════════════════════════════════

-- Every mutual pair, once per direction (a → b and b → a).
create or replace view public.friend_pairs with (security_invoker = true) as
  select f1.follower_id as a, f1.following_id as b, greatest(f1.created_at, f2.created_at) as since
  from public.follows f1
  join public.follows f2 on f2.follower_id = f1.following_id and f2.following_id = f1.follower_id;

create or replace function public.are_friends(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.follows x where x.follower_id = a and x.following_id = b)
     and exists (select 1 from public.follows y where y.follower_id = b and y.following_id = a)
     and not public.is_blocked_between(a, b);
$$;

-- You cannot follow someone while a block exists between you, in either direction.
drop policy if exists "follows: insert own" on public.follows;
create policy "follows: insert own" on public.follows for insert
  with check (follower_id = auth.uid() and follower_id <> following_id
              and not public.is_blocked_between(follower_id, following_id));

-- The request/accept flow is gone; pending/accepted rows are meaningless now.
drop function if exists public.friend_request(uuid);
drop function if exists public.friend_respond(uuid, boolean);
drop function if exists public.friend_remove(uuid);
drop trigger if exists friendships_notify on public.friendships;
drop function if exists public.notify_on_friendship();
delete from public.friendships where status <> 'blocked';

-- Follow notification, plus "you're now friends" for the person whose follow completed the pair.
create or replace function public.notify_on_follow() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications (user_id, type, from_user_id) values (new.following_id, 'follow', new.follower_id);
  if exists (select 1 from public.follows r where r.follower_id = new.following_id and r.following_id = new.follower_id) then
    insert into public.notifications (user_id, type, from_user_id) values (new.follower_id, 'friend_accepted', new.following_id);
  end if;
  return new;
end $$;

create or replace function public.friends_now_playing()
returns table (id uuid, username text, avatar_url text, accent_color text, supporter_until timestamptz,
               status_text text, status_emoji text, last_seen_at timestamptz,
               now_playing_id uuid, now_playing_at timestamptz, now_playing_source text,
               np_title text, np_artist text, np_cover text)
language sql stable as $$
  select p.id, p.username, p.avatar_url, p.accent_color, p.supporter_until,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_text end,
         case when p.status_expires_at is null or p.status_expires_at > now() then p.status_emoji end,
         p.last_seen_at,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_id end,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_at end,
         case when p.now_playing_at > now() - interval '30 minutes' then p.now_playing_source end,
         ci.title, ci.artist_name, ci.cover_url
  from public.friend_pairs fp
  join public.profiles p on p.id = fp.b
  left join public.catalog_items ci on ci.id = p.now_playing_id and p.now_playing_at > now() - interval '30 minutes'
  where fp.a = auth.uid() and not public.is_blocked_between(fp.a, fp.b)
  order by (p.now_playing_at > now() - interval '30 minutes') desc nulls last, p.last_seen_at desc nulls last;
$$;

create or replace function public.profile_stats(p_user uuid) returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'ratings',       (select count(*) from public.ratings where user_id = p_user),
    'reviews',       (select count(*) from public.ratings where user_id = p_user and nullif(review,'') is not null),
    'track_ratings', (select count(*) from public.track_ratings where user_id = p_user),
    'lists',         (select count(*) from public.lists where user_id = p_user),
    'followers',     (select count(*) from public.follows where following_id = p_user),
    'following',     (select count(*) from public.follows where follower_id = p_user),
    'friends',       (select count(*) from public.friend_pairs where a = p_user),
    'avg_rating',    (select round(avg(rating)::numeric, 2) from public.ratings where user_id = p_user),
    'this_month',    (select count(*) from public.ratings where user_id = p_user and created_at >= date_trunc('month', now())),
    'distribution',  (select jsonb_agg(jsonb_build_object('bucket', b.bucket, 'n', coalesce(c.n, 0)) order by b.bucket)
                      from (select unnest(array[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5]::numeric[]) as bucket) b
                      left join (select rating, count(*) as n from public.ratings where user_id = p_user group by rating) c on c.rating = b.bucket)
  );
$$;

create or replace function public.activity_feed(p_limit int default 30, p_before timestamptz default null)
returns table (kind text, id uuid, actor_id uuid, actor_username text, actor_avatar text, actor_accent text,
               actor_supporter_until timestamptz, created_at timestamptz, payload jsonb)
language sql stable as $$
  with who as (select following_id as id from public.follows where follower_id = auth.uid())
  select * from (
    select 'rating'::text, r.id, r.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, r.created_at,
           jsonb_build_object('item_id', r.catalog_item_id, 'legacy_album_id', r.album_id,
             'title', coalesce(ci.title, r.album_title), 'artist', ci.artist_name,
             'cover', coalesce(ci.cover_url, r.album_cover), 'rating', r.rating, 'review', r.review,
             'like_count', (select count(*) from public.review_likes l where l.rating_id = r.id),
             'liked_by_me', exists (select 1 from public.review_likes l where l.rating_id = r.id and l.user_id = auth.uid()))
    from public.ratings r join who on who.id = r.user_id join public.profiles p on p.id = r.user_id
    left join public.catalog_items ci on ci.id = r.catalog_item_id
    union all
    select 'track_rating', t.id, t.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, t.created_at,
           jsonb_build_object('item_id', t.catalog_item_id, 'album_item_id', t.album_item_id,
             'title', coalesce(ci.title, t.track_title), 'artist', ci.artist_name,
             'cover', coalesce(ci.cover_url, t.track_cover), 'rating', t.rating, 'review', t.review)
    from public.track_ratings t join who on who.id = t.user_id join public.profiles p on p.id = t.user_id
    left join public.catalog_items ci on ci.id = t.catalog_item_id
    union all
    select 'list', l.id, l.user_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, l.created_at,
           jsonb_build_object('title', l.title, 'type', l.type, 'item_count', jsonb_array_length(coalesce(l.items, '[]'::jsonb)),
             'covers', (select jsonb_agg(i->>'cover') from (select i from jsonb_array_elements(coalesce(l.items,'[]'::jsonb)) i limit 4) s))
    from public.lists l join who on who.id = l.user_id join public.profiles p on p.id = l.user_id
    union all
    -- "became friends": the follow that completed a mutual pair, from either side you follow
    select 'friendship', f.id, f.follower_id, p.username, p.avatar_url, p.accent_color, p.supporter_until, f.created_at,
           jsonb_build_object('other_id', o.id, 'other_username', o.username, 'other_avatar', o.avatar_url)
    from public.follows f
    join public.follows r on r.follower_id = f.following_id and r.following_id = f.follower_id and r.created_at <= f.created_at
    join who on who.id in (f.follower_id, f.following_id)
    join public.profiles p on p.id = f.follower_id
    join public.profiles o on o.id = f.following_id
  ) x
  where p_before is null or x.created_at < p_before
  order by x.created_at desc
  limit p_limit;
$$;
