/**
 * The hero-background pool from v1 (~60 records). Resolved by the warm-catalog job so the
 * landing page has covers before anyone has rated anything. Title/artist only — no provider
 * ids live in source code (§11 #1).
 */
export const HERO_ALBUMS: { title: string; artist: string }[] = [
	{ title: 'Midnights', artist: 'Taylor Swift' },
	{ title: 'Renaissance', artist: 'Beyoncé' },
	{ title: 'Un Verano Sin Ti', artist: 'Bad Bunny' },
	{ title: 'Mr. Morale & The Big Steppers', artist: 'Kendrick Lamar' },
	{ title: 'GNX', artist: 'Kendrick Lamar' },
	{ title: 'Hit Me Hard and Soft', artist: 'Billie Eilish' },
	{ title: 'Happier Than Ever', artist: 'Billie Eilish' },
	{ title: 'After Hours', artist: 'The Weeknd' },
	{ title: 'Future Nostalgia', artist: 'Dua Lipa' },
	{ title: 'Fine Line', artist: 'Harry Styles' },
	{ title: 'IGOR', artist: 'Tyler, The Creator' },
	{ title: 'Random Access Memories', artist: 'Daft Punk' },
	{ title: 'AM', artist: 'Arctic Monkeys' },
	{ title: 'Blonde', artist: 'Frank Ocean' },
	{ title: 'To Pimp a Butterfly', artist: 'Kendrick Lamar' },
	{ title: 'OK Computer', artist: 'Radiohead' },
	{ title: 'The Dark Side of the Moon', artist: 'Pink Floyd' },
	{ title: 'Rumours', artist: 'Fleetwood Mac' },
	{ title: 'In Rainbows', artist: 'Radiohead' },
	{ title: 'Currents', artist: 'Tame Impala' },
	{ title: 'Fetch the Bolt Cutters', artist: 'Fiona Apple' },
	{ title: 'Nevermind', artist: 'Nirvana' },
	{ title: 'Thriller', artist: 'Michael Jackson' },
	{ title: 'Purple Rain', artist: 'Prince' },
	{ title: 'Kind of Blue', artist: 'Miles Davis' },
	{ title: "What's Going On", artist: 'Marvin Gaye' },
	{ title: 'Innervisions', artist: 'Stevie Wonder' },
	{ title: 'Exile on Main St.', artist: 'The Rolling Stones' },
	{ title: 'Led Zeppelin IV', artist: 'Led Zeppelin' },
	{ title: 'The Velvet Underground & Nico', artist: 'The Velvet Underground' },
	{ title: 'Pet Sounds', artist: 'The Beach Boys' },
	{ title: 'Revolver', artist: 'The Beatles' },
	{ title: 'Abbey Road', artist: 'The Beatles' },
	{ title: 'The Chronic', artist: 'Dr. Dre' },
	{ title: 'Illmatic', artist: 'Nas' },
	{ title: 'Ready to Die', artist: 'The Notorious B.I.G.' },
	{ title: 'Enter the Wu-Tang (36 Chambers)', artist: 'Wu-Tang Clan' },
	{ title: 'Straight Outta Compton', artist: 'N.W.A.' },
	{ title: 'Reasonable Doubt', artist: 'JAY-Z' },
	{ title: 'The Miseducation of Lauryn Hill', artist: 'Lauryn Hill' },
	{ title: 'Loveless', artist: 'My Bloody Valentine' },
	{ title: 'Doolittle', artist: 'Pixies' },
	{ title: 'Dummy', artist: 'Portishead' },
	{ title: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West' },
	{ title: 'The College Dropout', artist: 'Kanye West' },
	{ title: 'Late Registration', artist: 'Kanye West' },
	{ title: 'Graduation', artist: 'Kanye West' },
	{ title: '808s & Heartbreak', artist: 'Kanye West' },
	{ title: 'Yeezus', artist: 'Kanye West' },
	{ title: 'The Life of Pablo', artist: 'Kanye West' },
	{ title: 'Donda', artist: 'Kanye West' },
	{ title: 'Let It Bleed', artist: 'The Rolling Stones' },
	{ title: 'Sticky Fingers', artist: 'The Rolling Stones' },
	{ title: 'Born to Run', artist: 'Bruce Springsteen' },
	{ title: 'Wish You Were Here', artist: 'Pink Floyd' },
	{ title: 'Animals', artist: 'Pink Floyd' },
	{ title: 'Aladdin Sane', artist: 'David Bowie' },
	{ title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', artist: 'David Bowie' },
	{ title: 'Unknown Pleasures', artist: 'Joy Division' },
	{ title: 'Disintegration', artist: 'The Cure' },
	{ title: 'Funeral', artist: 'Arcade Fire' },
	{ title: '"Awaken, My Love!"', artist: 'Childish Gambino' },
	{ title: 'Channel Orange', artist: 'Frank Ocean' },
	{ title: 'Discovery', artist: 'Daft Punk' },
	{ title: 'Kid A', artist: 'Radiohead' },
	{ title: 'Yoshimi Battles the Pink Robots', artist: 'The Flaming Lips' }
];
